language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
sudo: enabled
dist: trusty
dd:
- openssl aes-256-cbc -K $encrypted_2d374cd4b54f_key -iv $encrypted_2d374cd4b54f_iv
  -in credentials.json.enc -out credentials.json -d
