site_name: DEA Discord Bot
repo_url: https://github.com/RealBlazeIt/DEA
pages:
    - Home: index.md
    - Introduction: introduction.md
    - Setup: setup.md
    - Commands: commands.md
theme: readthedocs
